/***************************************************************************//**
 * @file
 * @brief General Purpose IO (GPIO) peripheral API for the TDxxxx RF modules.
 * @author Telecom Design S.A.
 * @version 2.0.2
 ******************************************************************************
 * @section License
 * <b>(C) Copyright 2012-2014 Telecom Design S.A., http://www.telecomdesign.fr</b>
 ******************************************************************************
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 * DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Telecom Design SA has no
 * obligation to support this Software. Telecom Design SA is providing the
 * Software "AS IS", with no express or implied warranties of any kind,
 * including, but not limited to, any implied warranties of merchantability
 * or fitness for any particular purpose or warranties against infringement
 * of any proprietary rights of a third party.
 *
 * Telecom Design SA will not be liable for any consequential, incidental, or
 * special damages, or any other relief, or for any claim by any third party,
 * arising from your use of this Software.
 *
  ******************************************************************************/

#include <stdint.h>
#include <stdbool.h>

#include <em_cmu.h>
#include <em_gpio.h>

#include "td_core.h"
#include "td_gpio.h"
#include "td_utils.h"
#include "td_rtc.h"
#include "td_printf.h"

/***************************************************************************//**
 * @addtogroup GPIO
 * @brief General Purpose IO (GPIO) peripheral API for the TDxxxx RF modules
 * @{
 ******************************************************************************/

/*******************************************************************************
 **************************   PUBLIC VARIABLES   *******************************
 ******************************************************************************/

/** @addtogroup GPIO_GLOBAL_VARIABLES Global Variables
 * @{ */

/** Array of GPIO IRQ hooks for system/user/odd/even IRQs */
TD_GPIO_hook_t TD_GPIO_Hooks[TD_GPIO_MAX_HOOKS];

/** @} */

#ifdef __ICCARM__
#pragma optimize = speed
#else
#pragma GCC optimize ("O3")
#endif

/*******************************************************************************
 **************************   PUBLIC FUNCTIONS   *******************************
 ******************************************************************************/

/** @addtogroup GPIO_USER_FUNCTIONS User Functions
 * @{ */

/***************************************************************************//**
 * @brief
 *   GPIO odd interrupt handler
 *
 * @details
 *   This function is automatically called by the hardware upon incoming
 *   interrupt generated by an odd-numbered GPIO pin.
 ******************************************************************************/
void GPIO_ODD_IRQHandler(void)
{
	uint32_t flag;
	uint32_t system_mask = TD_GPIO_Hooks[TD_GPIO_SYSTEM_ODD].mask;
	uint32_t user_mask = TD_GPIO_Hooks[TD_GPIO_USER_ODD].mask;

	// Get interrupt bits
	flag = (GPIO_IntGet() & TD_GPIO_ODD_MASK) & GPIO_IntGetEnabled();

	// Acknowledge IRQ
	// We acknowledge all IRQ read, for this IRQ (EVEN) and enabled
	// even if theses IRQ are not used (otherwise, it will infinitely reenter in this IRQ)
	GPIO_IntClear(flag);
#ifdef WAKE_MAIN_LOOP_DEBUG
	tfp_printf("IO:0x%08X\r\n");
#endif

	// System hook set on odd IRQ
	if (TD_GPIO_Hooks[TD_GPIO_SYSTEM_ODD].callback && (flag & system_mask)) {

		// Call the IRQ hook
		TD_GPIO_Hooks[TD_GPIO_SYSTEM_ODD].callback(flag & system_mask);

		// Remember that this interrupt source has been processed
		flag &= ~system_mask;
		TD_WakeMainLoop();
	}

	// User hook on odd IRQ
	if (TD_GPIO_Hooks[TD_GPIO_USER_ODD].callback && (flag & user_mask)) {

		// Call the IRQ hook
		TD_GPIO_Hooks[TD_GPIO_USER_ODD].callback(flag & user_mask);
		TD_WakeMainLoop();
	}
}

/***************************************************************************//**
 * @brief
 *   GPIO even interrupt handler
 *
 * @details
 *   This function is automatically called by the hardware upon incoming
 *   interrupt generated by an even-numbered GPIO pin.
 ******************************************************************************/
void GPIO_EVEN_IRQHandler(void)
{
	uint32_t flag;
	uint32_t system_mask = TD_GPIO_Hooks[TD_GPIO_SYSTEM_EVEN].mask;
	uint32_t user_mask = TD_GPIO_Hooks[TD_GPIO_USER_EVEN].mask;

	// Get interrupt bits
	flag = GPIO_IntGet() & TD_GPIO_EVEN_MASK & GPIO_IntGetEnabled();

	// Acknowledge IRQ.
	// We acknowledge all IRQ read, for this IRQ (EVEN) and enabled
	// even if theses IRQ are not used (otherwise, it will infinitely reenter in this IRQ)
	GPIO_IntClear(flag);
#ifdef WAKE_MAIN_LOOP_DEBUG
	tfp_printf("IO:0x%08X\r\n");
#endif
	// System hook set on odd IRQ
	if (TD_GPIO_Hooks[TD_GPIO_SYSTEM_EVEN].callback && (flag & system_mask)) {

		// Call the IRQ hook
		TD_GPIO_Hooks[TD_GPIO_SYSTEM_EVEN].callback(flag & system_mask);

		// Remember that this interrupt source has been processed
		flag &= ~system_mask;
		TD_WakeMainLoop();
	}

	// User hook on even IRQ
	if (TD_GPIO_Hooks[TD_GPIO_USER_EVEN].callback && (flag & user_mask)) {

		// Call the IRQ hook
		TD_GPIO_Hooks[TD_GPIO_USER_EVEN].callback(flag & user_mask);
		TD_WakeMainLoop();
	}
}

/***************************************************************************//**
 * @brief
 *   Initialize the GPIO peripheral for the TDxxxx RF modules.
 ******************************************************************************/
void TD_GPIO_Init(void)
{

	// Enable the GPIO module clock
	CMU_ClockEnable(cmuClock_GPIO, true);

	// Start LFXO and wait until it is stable
	CMU_OscillatorEnable(cmuOsc_LFXO, true, true);

	// Initialize IRQ hooks
	memset(TD_GPIO_Hooks, 0, sizeof(TD_GPIO_hook_t)*TD_GPIO_MAX_HOOKS);
}

/***************************************************************************//**
 * @brief
 *   Dump all GPIO configuration
 ******************************************************************************/
void TD_GPIO_Dump(void)
{
	uint8_t i, j, md;
	uint64_t mode;
	uint32_t d;
	char *txt;
	for (i = 0; i < 6; i++) {
		tfp_printf("--Port%c--\r\n", 'A' + i);
		mode = GPIO->P[i].MODEL;
		mode = mode | (((uint64_t)GPIO->P[i].MODEH) << 32);
		d = GPIO->P[i].DOUT;
		for (j = 0; j < 16; j++) {
			md = mode & 0xF;
			mode = mode >> 4;
			switch (md) {
			case 0:
				txt = "DIS";
				break;
			case 1:
				txt = "IN";
				break;
			case 2:
				txt = "INP";
				break;
			case 3:
				txt = "INPF";
				break;
			case 4:
				txt = "OUT";
				break;
			case 5:
				txt = "OUTD";
				break;
			case 6:
				txt = "WOR";
				break;
			case 7:
				txt = "WORP";
				break;
			case 8:
				txt = "WAN";
				break;
			case 9:
				txt = "WANF";
				break;
			case 10:
				txt = "WANP";
				break;
			case 11:
				txt = "WANPF";
				break;
			case 12:
				txt = "WAND";
				break;
			case 13:
				txt = "WANDF";
				break;
			case 14:
				txt = "WANDP";
				break;
			case 15:
				txt = "WANDPF";
				break;
			}
			tfp_printf("%01X)%6s:%d|  ", j, txt, d & 1);
			d >>= 1;
			if ((j & 3) == 3) {
				tfp_printf("\r\n");
			}
		}
	}
}
/** @} */

/** @} (end addtogroup GPIO) */
